name: pipeline

on:
  push:
      branches:
        - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Unit Tests
    steps: 
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '24'
      - uses: gradle/actions/setup-gradle@v4
      - run: ./gradlew test
      
  build:
    runs-on: ubuntu-latest
    name: Build
    steps: 
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '24'
      - uses: gradle/actions/setup-gradle@v4
      - run: ./gradlew build
